version: '3'

services:
  one-frame-service:
    image: paidyinc/one-frame
    container_name: one-frame-service
    ports:
      - "8090:8080"

  prometheus:
    image: prom/prometheus:v2.37.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:9.3.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # Your Scala application
  scala-app:
    build: .
    ports:
      - "8080:8080"  # Adjust if your app uses a different port
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:14250
    depends_on:
      - prometheus
      - jaeger