{
 "title": "Scala-App",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request Per Minute ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=\"scala-app\"}[1m])) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=\"scala-app\"}) by (route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CallWrapper Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(callwrapper_seconds_count{job=\"scala-app\"}) by (name,cached)",
     "legendFormat": "{{name}}-cached-{{cached}}"
    }
   ]
  }
 ]
}