# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Run tests
      run: sbt test
    - name: Cache sbt dependencies
      uses: actions/cache@v1
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - name: Build Docker Image
      run: docker build -t my-scala-app .

    - name: Dummy Push to container registry
      run: |
        echo "Simulating Docker login..."
        echo "${{ secrets.DOCKER_PASSWORD }}" 
        echo "docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin"
        echo "docker push success"
        echo



